name: Test Scripts

on:
  push:
    branches:
      - main
      - fixing-directories
  pull_request:
    branches:
      - main
      - fixing-directories

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies and DEBUG
      run: |
        echo "--- 1. Listing all files in the repository ---"
        ls -R
        echo "\n--- 2. Checking contents of requirements.txt ---"
        cat requirements.txt
        echo "\n--- 3. Installing dependencies ---"
        python -m pip install --upgrade pip
        pip install -r primekg-rag/requirements.txt
        python -m pip install pyvis

    - name: Test scripts
      run: |
        streamlit run client.py --server.headless true