name: Test Scripts

on:
  push:
    branches:
      - main
      - fixing-directories
  pull_request:
    branches:
      - main
      - fixing-directories

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies and DEBUG
      working-directory: ./primekg-rag
      run: |
        echo "--- 1. Listing all files in the repository ---"
        ls -R
        echo "\n--- 2. Checking contents of requirements.txt ---"
        cat requirements.txt
        echo "\n--- 3. Installing dependencies ---"
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m pip install pyvis

    - name: Test scripts
      working-directory: ./primekg-rag
      run: |
        # MODIFIED: Run Streamlit in the background, wait, and then stop it.
        # This checks if the app can start without crashing and allows the job to finish.
        streamlit run client.py --server.headless true &
        PID=$!
        sleep 15 # Wait for 15 seconds to see if it crashes
        kill $PID
