name: Test Scripts

on:
  push:
    branches:
      - main
      - fixing-directories
  pull_request:
    branches:
      - main
      - fixing-directories

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      # MODIFIED: Added this line to correctly handle Git submodules like 'scihub.py'
      with:
        submodules: 'recursive'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies and DEBUG
      # MODIFIED: Set the working directory to where your files are located
      working-directory: ./primekg-rag
      run: |
        echo "--- 1. Listing all files in the repository ---"
        ls -R
        echo "\n--- 2. Checking contents of requirements.txt ---"
        cat requirements.txt
        echo "\n--- 3. Installing dependencies ---"
        python -m pip install --upgrade pip
        # Path is now correct relative to the working directory
        pip install -r requirements.txt
        python -m pip install pyvis

    - name: Test scripts
      # MODIFIED: Set the working directory for the test step as well
      working-directory: ./primekg-rag
      run: |
        # Path is now correct relative to the working directory
        streamlit run client.py --server.headless true
